name: "Semantic Pull Requests"

on:
  merge_group:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  main:
    runs-on: ubuntu-latest
    name: Validate PR
    steps:
      - name: Check PR
        uses: aruba-uxi/semantic-pull-request-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
